# Numpy
## Agenda:
* Introduction to Numpy.
* Array Creation Routines.
* Examples.
* Array Creation from Existing Data
* Examples.

## Introduction to Numpy:
* It is a Fast Mathematical Computational Library.
* Implemented using C. 
* Dealts with homogenous data structures.
* Specialized for doing mathematical computations on high dimensional data. 
* It provides inbuilt utilities which are mutable in nature.
* As mentiond above it is using C internally, so it is fast in nature when it 
   compared to general purpose library using list available in Python.
 
## Array creation routines:
Arrays in numpy can be created in multiple ways. Let's see them one by one.

Array creation routines:
* Using Empty.
* Using Eye.
* Using One init.
* Using Zero init.
* From default value initialization(Full init)
* Using Range.
* Using Linspace
* Using Random.


Import Numpy Library as np using below statement.

In [331]:
import numpy as np

### Using Empty:

#### empty:
* Return a new array of given shape and type, without initializing/arbitrary entries.

In [326]:
np.empty([2, 2])

array([[  1.16962778e-311,   1.97626258e-323],
       [  1.58101007e-322,   3.95252517e-323]])

In [268]:
np.empty([2, 2], dtype=int)

array([[1998615401, 1768453225],
       [1852776558, 1718558821]])

#### empty_like:
* Return a new array with the same shape and type as a given array.

In [325]:
a = ([1,2,3], [4,5,6]) 
np.empty_like(a)

array([[3, 0, 3],
       [0, 1, 0]])

* we got the new array empty_array_copy with size of (a) but contents are arbitrary.

### Using Eye:

#### eye:
* Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [323]:
np.eye(N=3,M=2,k=0,dtype=int)

array([[1, 0],
       [0, 1],
       [0, 0]])

* Here, <br />
N = Number of rows <br />
M = Nuber of columns <br />
k = Index of the diagonal(positive value refers to an upper diagonal, and a negative value to a lower diagonal.)

In [322]:
np.eye(N=3,k=-1)

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

### Using One Init:

#### ones:
* Initializes all values in array to 1.

In [321]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [320]:
np.ones(shape=(2,2,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

#### ones_like:
* creates new data structure with same dimension/size.

In [319]:
np.ones_like(ones_array3D)

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

### Using Zero init:

#### zeros:

In [318]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [317]:
np.zeros(shape=(2,2,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

#### zeros_like:

* same as mention before creates a new array with same dimention.

In [315]:
np.zeros_like(zeros_array3D)

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

### From default value initialization(Full init):

#### full:
* It initializes all the values in array to given value.

In [314]:
np.full(shape=(6,6),fill_value=99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [313]:
np.full(shape=(3,2),fill_value='hello')

array([['hello', 'hello'],
       ['hello', 'hello'],
       ['hello', 'hello']],
      dtype='<U5')

#### full_like:

In [312]:
np.full_like(array_d,'hello')

array([['hello', 'hello'],
       ['hello', 'hello'],
       ['hello', 'hello']],
      dtype='<U5')

* Just remember we need to pass both array and fill_value to full_like function.

### Using Range:

* It returns evenly spaced values within the given interval.

In [311]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

* In above Example params are (start=10,stop=20,step=2)
* Here, we can see that it included start value(10) but excluded stop value 20 and returned values with step size 2.
* So, remember it always generates values within the half-open interval [start, stop).

In [310]:
np.arange(15,10,-1)

array([15, 14, 13, 12, 11])

* arange function also works with negative and non-integer(eg:0.1) step size.
* But for non-integer the results will often not be consistent.
* It is better to use linspace for non integer step cases.

### Using Linspace:

* It is also returns evenly spaced values  withing given interval like range function.
* But unlike range function it includes both start and stop values by default(eg: [start,stop]).
* optionally we can exclude stop value from interval(eg: [start,stop)).


In [309]:
np.linspace(2.0, 3.0, num=5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

* Here, linspace returned 5 evenly spaced values within interval [start=2.0,stop=3.0].

In [308]:
np.linspace(2.0,3.0,num=5,endpoint=False)

array([ 2. ,  2.2,  2.4,  2.6,  2.8])

* If the endpoint is False it returns values within interval [start=2.0,stop=3.0)

### Using Random:
* Creates a array with given shape and populate it with random values.

#### rand:
* Populates random values within interval [0,1).
* In statistical terms it returns random samples from a uniform distribution over [0, 1).

In [307]:
np.random.rand(10)

array([ 0.07144605,  0.56268769,  0.70179016,  0.49174631,  0.30628691,
        0.52335683,  0.18217714,  0.10920607,  0.10803223,  0.60445098])

In [306]:
np.random.rand(3,2)

array([[ 0.69055771,  0.18017498],
       [ 0.50338971,  0.07918502],
       [ 0.90105452,  0.49737752]])

#### randn:
* It fills sample values from the “standard normal” distribution.
* standard normal distribution means mean is equal to 0 and variance is equal to 1.

In [305]:
np.random.randn(2,4)

array([[ 2.20060746,  0.37324182,  0.73642848, -0.96839575],
       [-0.32664876,  1.78067469, -0.04714109, -0.99208077]])

* randn function returns a single float randomly sampled from the distribution is returned if no argument is provided.
* see the example below.

In [304]:
np.random.randn()

-0.554174466044771

#### randint:
* randint return random integers from low (inclusive) to high (exclusive).
* size and  high value is optional.
* in statistical terms return random integers from the “discrete uniform” distribution. 

In [303]:
np.random.randint(low=5,high=10,size=(3,3))

array([[7, 8, 5],
       [5, 9, 9],
       [7, 5, 8]])

In [302]:
np.random.randint(low=5)

0

In [334]:
np.random.randint(low=5,size=10)

array([2, 0, 0, 0, 1, 0, 1, 3, 0, 1])