# Agenda
  * Numpy Accessing Elements with exmaples
  * Creating copies of arrays
  * Numpy -Indexing & Slicing
  * Reshaping Data
  * Adding Dimensions
  * Stacking [ Verical & Horizontal & dstack ]
  * Splitting [np.split & Vertical & Horizontal & dsplit] 

### Numpy Accessing Elements

In [4]:
import numpy as np

### Creating copies of arrays

In [5]:
x2=np.random.randint(2,20,size=(5,5))
x2

array([[17, 16,  4, 19, 10],
       [10, 17,  8, 17,  4],
       [15, 14, 11, 14, 16],
       [ 2, 18, 16,  5,  8],
       [ 3, 14,  5, 14,  3]])

In [6]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[17 16]
 [10 17]]


### NumPy - Indexing & Slicing

### slice function
* slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

#### slice(start:stop:step)

In [7]:
a = np.arange(10) 
s=slice(2,7,2) 
print (a[s])

[2 4 6]


*  The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object

In [8]:
b = a[2:7:2] 
print (b)

[2 4 6]


In [9]:
np.random.seed(10)
data = np.random.randint(2,20,size=(5,5))
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Two ways to access array

In [10]:
data[2][1]

10

In [11]:
data[2,1]

10

#### Accessing only the first row

In [32]:
data[:1]

array([[11,  6, 17,  2, 19]])

#### Accessing till row 2

In [13]:
data[:2]

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2]])

#### Column access

In [14]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [15]:
data[:,1:3]

array([[ 6, 17],
       [19, 10],
       [10,  6],
       [13, 13],
       [16, 19]])

#### Accessing centered data 

*  In below example we are accesing the centered data from indexes row:1-3 using index[1:4] and column:1-3 using index[1:4]

In [16]:
data[1:4,1:4]

array([[19, 10, 11],
       [10,  6, 18],
       [13, 13,  3]])

*  In below example the output [1 4 5] is retrived from indexes (0,0)(1,1)(2,0)

In [17]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


#### Shape, Size & Dimension
* These are not functions but attributes

#### shape provides the number of rows and colums

In [121]:
data.shape 

(5, 5)

#### size provides the number of elements in an array

In [122]:
data.size 

25

#### ndim - returns number of dimensions of an array

* In below example data is of 2 dimension

In [123]:
data.ndim 

2

In [124]:
data2=np.arange(0,32).reshape(2,4,4)

In [125]:
data2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [127]:
data2.ndim

3

*  In above example data2 has 3 dimensions

#### Reshaping data
Changes shape & dimension of data but not size

In [21]:
a = np.array([1,2,3,4,5,6])

*  Here 'a' is one dimension array

In [22]:
a.shape

(6,)

In [23]:
a.ndim

1

In [98]:
a=a.reshape((2,3))

*  after reshaping 'a' is two dimension array but its elements are not changed or removed

In [128]:
a.shape

(2, 3)

#### Reducing dimension using reshape

In [105]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
In below we are reshaping the x into one dimension row array

In [136]:
y = x.reshape(-1)
y

array([1, 2, 3, 4, 5, 6, 7, 8])

*  Output for below example Is a 2 dimensional columnar array
*  reshape(-1,1) will add one new dimention

In [109]:
g = np.arange(10).reshape((1,-1))
g.shape

(1, 10)

In [137]:
g

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [138]:
g.shape

(1, 10)

*  Output for below example Is a 1 dimensional row array

In [139]:
f=np.arange(10).reshape((-1,1))
f

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### Example fo reshape()

In [59]:
a

array([1, 2, 3, 4, 5, 6])

In [60]:
c=a.reshape(-1,1)
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [61]:
d=a.reshape(-1,2)
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
b.ndim

2

In [64]:
b.shape

(2, 3)

In [65]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
b.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

### Adding one dim

In [142]:
a = np.array([1,2,3,4,5,6])

In [143]:
a.ndim

1

In [148]:
a.shape[0]

6

#### Adds one dimension

In [145]:
b=a.reshape((a.shape[0],1))

In [147]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

#### Yet another way to add one more dimension

In [149]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [150]:
a.shape

(6,)

In [154]:
data=data[:,np.newaxis]

In [156]:
data

array([[[11,  6, 17,  2, 19]],

       [[18, 19, 10, 11,  2]],

       [[12, 10,  6, 18,  6]],

       [[17, 13, 13,  3, 10]],

       [[ 6, 16, 19, 15,  7]]])

In [155]:
data.ndim

3

#### Convert data into 1-d of 25 elements¶

In [159]:
data=data.reshape(25)
data

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

In [160]:
data.reshape(*data.shape,1).shape

(25, 1)

#### removal of dimension , converts into 1D data .i.e flattens it out

In [161]:
np.ravel(data)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

#### Concatination
Combining data

#### Combining 1-D data

In [162]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [163]:
np.concatenate([x,y,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

#### Axis
* 0 - vertical
* 1 - horizontal

#### Combining 2D data
* by default axis zero

In [173]:
d=np.arange(1,26).reshape(5,5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### vetical concatenate (default axis=0)

In [174]:
np.concatenate([d,d])  

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### horizontal concatenate axis = 1

In [175]:
np.concatenate([d,d],axis=1) 

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 21, 22, 23, 24, 25]])

#### append
* adds value at the end of the array

In [176]:
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Note: If we donot pass axis information it flattens the array and appends at the last

In [185]:
np.append(d,[[1,2,3,4,5]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25,  1,  2,  3,  4,  5])

*  with axis = 0

In [184]:
np.append(d,[[1,2,3,4,5]],axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [ 1,  2,  3,  4,  5]])

*  with axis =1

In [180]:
np.append(d,[[1],[2],[3],[4],[5]],axis=1)

array([[ 1,  2,  3,  4,  5,  1],
       [ 6,  7,  8,  9, 10,  2],
       [11, 12, 13, 14, 15,  3],
       [16, 17, 18, 19, 20,  4],
       [21, 22, 23, 24, 25,  5]])

In [ ]:
np.append(data, [[1,2,3,4,5]], axis=0)

## Stacking [ Verical & Horizontal Stacking, dstack ]:

#### Rules
* hstacking - num of rows should be same
* vstacking - num of cols should be same

### horizontal stacking¶

In [189]:
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [187]:
np.hstack([d,d])

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 21, 22, 23, 24, 25]])

### vertical stacking

In [188]:
np.vstack([d,d])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### dstack
* This is equivalent to concatenation along the third axis after 2-D arrays of shape (M,N) have been reshaped to (M,N,1) and 1-D arrays of shape (N,) have been reshaped to (1,N,1). Rebuilds arrays divided by dsplit.
* in below example  a and b are both two dimensional, np.dstack expands them by inserting a third dimension of size 1. This is equivalent to indexing them in the third dimension with np.newaxis

In [ ]:
 a = np.array((1,2,3))
 b = np.array((2,3,4))
 c=np.dstack((a,b))

In [ ]:
c

In [ ]:
c.shape

## Splitting

### np.split

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1 = np.split(x, [3, 5])
print(x1)

### hsplit - splitting the horizontal axis

In [ ]:
a,b=np.hsplit(data,[3])

In [ ]:
a

### vsplit - splitting the vertical axis

In [ ]:
a,b=np.vsplit(data,[2])

In [ ]:
b

In [ ]:
data

### dsplit

#### dsplit is equivalent to split with axis=2, the array is always split along the third axis provided the array dimension is greater than or equal to 3.

In [ ]:
x = np.arange(18.0)

In [ ]:
x

In [ ]:
y=x.reshape(2, 3, 3)

In [ ]:
y

In [ ]:
np.dsplit(y,3)

## Conclusion
In this chapter we seen the ways of accessing numpy elements. we will explore numpy functions using this knowledge in the next chapter.