# Agenda:
* Numpy Accessing Elements with exmaples
  * Creating copies of arrays
  * Numpy -Indexing & Slicing
  * Reshaping Data
  * Adding Dimensions
  * Stacking [ Verical & Horizontal & dstack ]
  * Splitting [np.split & Vertical & Horizontal & dsplit] 

## Numpy Accessing Elements

In [2]:
import numpy as np

## Creating copies of arrays

In [69]:
x2=np.random.randint(2,20,size=(5,5))

In [67]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[6 6]
 [5 8]]


## NumPy - Indexing & Slicing

#### slice function

#### slice(start:stop:step)

In [4]:
a = np.arange(10) 
s=slice(2,7,2) 
print (a[s])

[2 4 6]


#### The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object

In [5]:
b = a[2:7:2] 
print (b)

[2 4 6]


In [23]:
np.random.seed(10)
data = np.random.randint(2,20,size=(5,5))
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### Two ways to access this

In [24]:
data[2][1]

10

data[2,1]

#### Accessing only the first row

In [26]:
data[:1]

array([[11,  6, 17,  2, 19]])

#### Accessing till row 2

In [27]:
data[:2]

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2]])

#### Column access

In [33]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [34]:
data[:,1:3]

array([[ 6, 17],
       [19, 10],
       [10,  6],
       [13, 13],
       [16, 19]])

#### Accessing centered data 

In [40]:
data[1:4,1:4]

array([[19, 10, 11],
       [10,  6, 18],
       [13, 13,  3]])

In [42]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


#### Shape, Size & Dimension
* These are not functions but attributes

#### shape provides information on dimension

In [43]:
data.shape 

(5, 5)

#### Total size of data

In [45]:
data.size 

25

#### ndim - returns num of dimension

In [47]:
data.ndim 

2

### Reshaping data
Changes shape & dimension of data but not size

In [16]:
a = np.array([1,2,3,4,5,6])

In [51]:
a.shape

(6,)

In [52]:
a.ndim

1

In [53]:
b = a.reshape((2,3))

In [6]:
b

array([2, 4, 6])

#### reshape(-1,1) will add one new dimention  

In [25]:
c=a.reshape(-1,1)
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [26]:
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
b.ndim

2

In [56]:
b.shape

(2, 3)

In [57]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
b.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

### Adding one dim

In [59]:
a = np.array([1,2,3,4,5,6])

In [99]:
a.ndim

1

#### Adds one dimension

In [81]:
b=a.reshape((a.shape[0],1))

In [100]:
b.ndim

2

#### Yet another way to add one more dimension

In [87]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [93]:
a.shape

(6,)

In [89]:
data[:,np.newaxis]

array([[[11,  6, 17,  2, 19]],

       [[18, 19, 10, 11,  2]],

       [[12, 10,  6, 18,  6]],

       [[17, 13, 13,  3, 10]],

       [[ 6, 16, 19, 15,  7]]])

In [91]:
data.ndim

2

#### Convert data into 1-d of 25 elements¶

In [102]:
data.reshape(25)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

In [103]:
data.reshape(*data.shape,1).shape

(5, 5, 1)

#### removal of dimension , converts into 1D data .i.e flattens it out

In [106]:
np.ravel(data)

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7])

#### Concatination
Combining data

#### Combining 1-D data

In [107]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [108]:
np.concatenate([x,y,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

#### Axis
* 0 - vertical
* 1 - horizontal

#### Combining 2D data
* by default axis zero

In [109]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### vetical concatenate (default axis=0)

In [112]:
np.concatenate([data,data])  

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

#### horizontal concatenate axis = 1

In [113]:
np.concatenate([data,data],axis=1) 

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

#### append
* adds value at the end of the array

In [114]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [115]:
np.append(data,[1,2,3,4,5])

array([11,  6, 17,  2, 19, 18, 19, 10, 11,  2, 12, 10,  6, 18,  6, 17, 13,
       13,  3, 10,  6, 16, 19, 15,  7,  1,  2,  3,  4,  5])

In [126]:
np.append(data,[[1],[2],[3],[4],[5]],axis=1)

array([[11,  6, 17,  2, 19,  1],
       [18, 19, 10, 11,  2,  2],
       [12, 10,  6, 18,  6,  3],
       [17, 13, 13,  3, 10,  4],
       [ 6, 16, 19, 15,  7,  5]])

In [127]:
np.append(data, [[1,2,3,4,5]], axis=0)

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [ 1,  2,  3,  4,  5]])

## Stacking [ Verical & Horizontal Stacking, dstack ]:

#### Rules
* hstacking - num of rows should be same
* vstacking - num of cols should be same

### horizontal stacking¶

In [128]:
np.hstack([data,data])

array([[11,  6, 17,  2, 19, 11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2, 18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6, 12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10, 17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7,  6, 16, 19, 15,  7]])

### vertical stacking

In [129]:
np.vstack([data,data])

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7],
       [11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

### dstack
* This is equivalent to concatenation along the third axis after 2-D arrays of shape (M,N) have been reshaped to (M,N,1) and 1-D arrays of shape (N,) have been reshaped to (1,N,1). Rebuilds arrays divided by dsplit.
* in below example  a and b are both two dimensional, np.dstack expands them by inserting a third dimension of size 1. This is equivalent to indexing them in the third dimension with np.newaxis

In [91]:
 a = np.array((1,2,3))
 b = np.array((2,3,4))
 c=np.dstack((a,b))

In [44]:
c

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [38]:
c.shape

(1, 3, 2)

## Splitting

### np.split

In [71]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1 = np.split(x, [3, 5])
print(x1)

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


### hsplit - splitting the horizontal axis

In [152]:
a,b=np.hsplit(data,[3])

In [154]:
a

array([[11,  6, 17],
       [18, 19, 10],
       [12, 10,  6],
       [17, 13, 13],
       [ 6, 16, 19]])

### vsplit - splitting the vertical axis

In [148]:
a,b=np.vsplit(data,[2])

In [151]:
b

array([[12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [140]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

### dsplit

#### dsplit is equivalent to split with axis=2, the array is always split along the third axis provided the array dimension is greater than or equal to 3.

In [77]:
x = np.arange(18.0)

In [78]:
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.])

In [85]:
y=x.reshape(2, 3, 3)

In [90]:
y

array([[[  0.,   1.,   2.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.]],

       [[  9.,  10.,  11.],
        [ 12.,  13.,  14.],
        [ 15.,  16.,  17.]]])

In [89]:
np.dsplit(y,3)

[array([[[  0.],
         [  3.],
         [  6.]],
 
        [[  9.],
         [ 12.],
         [ 15.]]]), array([[[  1.],
         [  4.],
         [  7.]],
 
        [[ 10.],
         [ 13.],
         [ 16.]]]), array([[[  2.],
         [  5.],
         [  8.]],
 
        [[ 11.],
         [ 14.],
         [ 17.]]])]

## Conclusion:
In this chapter we seen the ways of accessing numpy elements. we will explore numpy functions using this knowledge in the next chapter.