# Agenda

* Introduction to Numpy Broadcasting
* Broadcasting Rules 
* Examples
       

## Introduction to Numpy Broadcasting

* The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations.
* Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then   these operations are smoothly performed.

#### Broadcasting is possible if the following rules are satisfied 

* Array with smaller ndim than the other is prepended with '1' in its shape.

* Size in each dimension of the output shape is maximum of the input sizes in that dimension.

* An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.

* If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.


#### A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true 

* Arrays have exactly the same shape.

* Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.

* Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.

In [10]:
import numpy as np

In [15]:
a = np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [17]:
b = np.array([ [1,2,3,4], [5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a + b

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [6]:
c = np.array([ [1,2,3,4], [5,6,7,8]])

In [7]:
b+c

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [8]:
b*c

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [9]:
b.shape

(2, 4)

In [10]:
b.ndim

2

In [11]:
a.shape

(4,)

#### In below image we can see that we have two arrays of different sizes (1,3) and(1,) so it is difficult to perform arithmetic operations   hence the second array  will be braodcasted with size (1,3) with values 6 in each box  so we can perform operations easily.

<img src="https://raw.githubusercontent.com/sharathchandu0007/data-science-notes/master/broadcast1.PNG"/>

<img src ="https://raw.githubusercontent.com/sharathchandu0007/data-science-notes/master/broadcast2.PNG"/>

<img src= "https://raw.githubusercontent.com/suresrividya/data-science-notes/master/broadcst3new.PNG"/>

#### In this image we have two arrays of size (3,3) and (1,3) to perform arithmetic operations the second array will be broacasted to size(3,3) with values similar in the second array 

<img src ="https://raw.githubusercontent.com/sharathchandu0007/data-science-notes/master/broadcast2.PNG"/>

#### In below image first array has shape (3,1) and Second array has shape (1,3) . Both the shapes are not in match with any of the dimension. Hence, the both arrays need to be broadcasted in ordered to perform any arithmetic operation

<img src= "https://raw.githubusercontent.com/suresrividya/data-science-notes/master/broadcst3new.PNG"/>

## Broadcasting Rules 

#### Rule 1
* The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

In [12]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

#### Rule 2
* The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

In [45]:
a = np.random.randint(10,size=(2,3))

In [46]:
b = np.random.randint(20, size=(3,4))

## Examples 

#### while multipying a*b it throws error because of shape of a and b dosent match

In [47]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,4) 

#### The shapes of both a and b are different ,so as of rule we will add 1's for which they are not matching a.shape=(2,3,1) and b.shape=(1,3,4)
* PS : There is more than one correct answer as long as rule is satisfied

In [48]:
a.reshape(2,3,1)

array([[[6],
        [4],
        [7]],

       [[3],
        [6],
        [0]]])

In [49]:
b.reshape(1,3,4)

array([[[ 9, 11,  4, 18],
        [11,  4,  9,  7],
        [ 4, 11,  4,  4]]])

In [50]:
a.reshape(2,3,1) + b.reshape(1,3,4)

array([[[15, 17, 10, 24],
        [15,  8, 13, 11],
        [11, 18, 11, 11]],

       [[12, 14,  7, 21],
        [17, 10, 15, 13],
        [ 4, 11,  4,  4]]])

#### example 2

In [33]:
a = np.random.randint(5,10,size=(2,3,4))
b = np.random.randint(5,10,size=(6,5))

#### In this example the sizes dosent match so as of rule we add 1's in the dimensions,where ever the values do not match

In [34]:
a.reshape(1,1,2,3,4) + b.reshape(6,5,1,1,1)

array([[[[[16, 16, 16, 16],
          [14, 12, 14, 15],
          [12, 16, 12, 15]],

         [[14, 14, 15, 12],
          [16, 13, 13, 14],
          [16, 12, 14, 15]]],


        [[[18, 18, 18, 18],
          [16, 14, 16, 17],
          [14, 18, 14, 17]],

         [[16, 16, 17, 14],
          [18, 15, 15, 16],
          [18, 14, 16, 17]]],


        [[[18, 18, 18, 18],
          [16, 14, 16, 17],
          [14, 18, 14, 17]],

         [[16, 16, 17, 14],
          [18, 15, 15, 16],
          [18, 14, 16, 17]]],


        [[[17, 17, 17, 17],
          [15, 13, 15, 16],
          [13, 17, 13, 16]],

         [[15, 15, 16, 13],
          [17, 14, 14, 15],
          [17, 13, 15, 16]]],


        [[[16, 16, 16, 16],
          [14, 12, 14, 15],
          [12, 16, 12, 15]],

         [[14, 14, 15, 12],
          [16, 13, 13, 14],
          [16, 12, 14, 15]]]],



       [[[[18, 18, 18, 18],
          [16, 14, 16, 17],
          [14, 18, 14, 17]],

         [[16, 16, 17, 14],
          [18,

## Conclusion

In this chapter we had discussed broadcasting and its rules with examples. To know data analysis with pandas please visit pandas series.